### ISSUE TITLE
lmdb hunter

### ISSUE THREAD

**Issue by exploshot** [who-biz/qwerty-lmdb#1]
hi @who-biz ,
hunter supports lmdb since 0.19.148
so you can theoretically add it like this:

```
hunter_add_package(lmdb)
find_package(liblmdb CONFIG REQUIRED)
```

**Comment by who-biz** [comment]
IIRC, the standard `lmdb` implementation drivers differ slightly from the drivers included for XMR/BLUR/QWC. But I could be wrong. 

I can double check. If there are no conflicts, I don't see why this couldn't be done.  Not sure if it adds additional overhead beyond what is built within the `QwertycoinFramework::LMDB` library, though.

**Comment by who-biz** [comment]
One other thing to consider @exploshot, would be dependency attacks, or simply inadvertent changes, that may cause nodes to re-interpret historical transaction data erroneously.   Pretty sure these kind of things are why `unbound`, `rapidjson`, `lmdb`, and `boost` (serialization-related) files are ported in as static submodules or built in-tree.

But, whatever you, Xecute, and the other devs would like to do outweighs my opinion on the matter.

**Comment by who-biz** [comment]
You'll notice that I removed hunter from this repository for the time that I am working.  I felt it was excessive to build boost from source each time, when it could be found on the compiler's host system.  So maybe a change best left for once the integrations are finished, at any rate.

**Comment by who-biz** [comment]
@exploshot i'll give the lmdb package a try today, since i'm debugging issues w/ the DB drivers, anyway
